name: Playwright Cucumber Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Cucumber tests
      run: cucumber-js
      env:
        CI: true
      timeout-minutes: 60
    - name: Upload Cucumber json report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-json-report
        path: cucumber_report.json
        retention-days: 30
    - name: Upload Cucumber html report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-html-report
        path: reports/cucumber_report.html
        retention-days: 30
        